name: Proto1-Backend

on:
  push:
    branches: [ main,dev ]
  # pull_request:
  #   branches: [ main,dev ]
  workflow_dispatch:

env:
  NODE_VERSION: '16.x'
  NODE_APP: 'proto1-backend'                # set this to the node version to use

permissions:
  contents: write

jobs:

  DeployDev:
    name: Deploy to Dev 
#    needs: [DeployDev]
    if: github.event.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: 
      name: dev
      #url: 'http://www.myapp.com'
    steps:       
    - name: Connect and pull
      run: ssh -i ${{ secrets.DEV_SSH_KEY}} ${{ secrets.DEV_SSH_USER }}@${{ secrets.DEV_SSH_HOST }} "cd ${{ secrets.DEV_SERVER_PATH }} && rm -irf !'(templates)' && git checkout ${{ secrets.DEV_BRANCH }} && git pull && exit"
    - name: Cleanup hiden files and dirs
      run: rm -r .[a-zA-Z_-]*

  DeployProd:
    name: Deploy to Production 
#    needs: [DeployDev]
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: 
      name: production
      #url: 'http://www.myapp.com'
    steps:
    - name: Connect and pull
      run: ssh -i ${{ secrets.PROD_SSH_KEY}} ${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }} "cd ${{ secrets.PROD_SERVER_PATH }} && rm -irf !'(templates)' && git checkout ${{ secrets.PROD_BRANCH }} && git pull && exit"
    - name: Cleanup hidden files and dirs
      run: rm -r .[a-zA-Z_-]*

