name: Proto1-Backend

on:
  push:
    branches: [ main,dev ]
  # pull_request:
  #   branches: [ main,dev ]
  workflow_dispatch:

env:
  NODE_VERSION: '16.x'
  NODE_APP: 'proto1-backend'                # set this to the node version to use

permissions:
  contents: write

jobs:

  DeployDev:
    name: Deploy to Dev 
#    needs: [DeployDev]
    if: github.event.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: 
      name: dev
      #url: 'http://www.myapp.com'
    steps: 
    - uses: actions/checkout@v3
    - name: Deploy backend code
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEV_SSH_HOST }}
        username: ${{ secrets.DEV_SSH_USER }}
        key: ${{ secrets.DEV_SSH_KEY }}
        port: ${{ secrets.DEV_SSH_PORT }}
        script: |
          cd ${{ secrets.DEV_SERVER_PATH }}
          rm -irf !(templates)
          git checkout ${{ secrets.DEV_BRANCH }}          
          git pull
          rm -r .[a-zA-Z_-]*
          echo "Before restarting Apache"
          sudo systemctl restart apache2
          echo "Deployed and Restarted Apache"

  DeployProd:
    name: Deploy to Production 
#    needs: [DeployDev]
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: 
      name: prod
      #url: 'http://www.myapp.com'
    steps: 
    - uses: actions/checkout@v3
    - name: Deploy backend code
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.PROD_SSH_HOST }}
        username: ${{ secrets.PROD_SSH_USER }}
        key: ${{ secrets.PROD_SSH_KEY }}
        port: ${{ secrets.PROD_SSH_PORT }}
        script: |
          cd ${{ secrets.PROD_SERVER_PATH }}
          rm -irf !(templates)
          git checkout ${{ secrets.PROD_BRANCH }}          
          git pull
          rm -r .[a-zA-Z_-]*
          echo "Before restarting Apache"
          sudo systemctl restart apache2
          echo "Deployed and Restarted Apache"