name: Proto1-Backend
on:
  push:
    branches: [ main,dev ]
  workflow_dispatch:

env:
  NODE_VERSION: '16.x'                # set this to the node version to use
  NODE_APP: 'Proto1-Backend'                

permissions:
  contents: write

jobs:
  DeployDev:
    name: Deploy to Dev 
    if: github.event.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps: 
    - uses: actions/checkout@v3
      with:
        ref: ${{ secrets.DEV_BRANCH }}
    - name: Deploy backend code
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEV_SSH_HOST }}
        username: ${{ secrets.DEV_SSH_USER }}
        key: ${{ secrets.DEV_SSH_KEY }}
        port: ${{ secrets.DEV_SSH_PORT }}
        script: |
          cd ${{ secrets.DEV_SERVER_PATH }}
          rm -irf !'(templates)'
          rm -rf .git*
          git init
          git config --global --add safe.directory ${{ secrets.DEV_SERVER_PATH }}
          echo "git pull https://${{secrets.GIT_PAT}}@github.com/${{ github.repository }}.git ${{ secrets.DEV_BRANCH }}"
          git pull https://${{secrets.GIT_PAT}}@github.com/${{ github.repository }}.git ${{ secrets.DEV_BRANCH }}
          rm -rf .[a-zA-Z_-]*
          echo "Before restarting Dev Apache"
          sudo systemctl restart apache2
          echo "Deployed and Restarted Dev Apache"

  DeployProd:
    name: Deploy to Production 
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: 
      name: prod
    steps: 
    - uses: actions/checkout@v3
      with:
        ref: ${{ secrets.PROD_BRANCH }}
    - name: Deploy backend code
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.PROD_SSH_HOST }}
        username: ${{ secrets.PROD_SSH_USER }}
        key: ${{ secrets.PROD_SSH_KEY }}
        port: ${{ secrets.PROD_SSH_PORT }}
        script: |
          cd ${{ secrets.PROD_SERVER_PATH }}
          echo "before removing old files"          
          rm -rf .git*
          rm -irf !"(templates)"
          echo "after removing old files"
          git init
          git config --global --add safe.directory ${{ secrets.PROD_SERVER_PATH }}
          echo "git pull https://${{secrets.GIT_PAT}}@github.com/${{ github.repository }}.git ${{ secrets.PROD_BRANCH }}"
          git pull https://${{secrets.GIT_PAT}}@github.com/${{ github.repository }}.git ${{ secrets.PROD_BRANCH }}
          rm -rf .git*
          echo "Before restarting Prod Apache"
          sudo systemctl restart apache2
          echo "Deployed and Restarted Prod Apache"



